-- CreateTable
CREATE TABLE `photos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `turnoId` INTEGER NOT NULL,
    `tipo` VARCHAR(100) NOT NULL,
    `checklistUuid` VARCHAR(36) NULL,
    `checklistPerguntaId` INTEGER NULL,
    `sequenciaAssinatura` INTEGER NULL,
    `servicoId` INTEGER NULL,
    `fileName` VARCHAR(255) NOT NULL,
    `mimeType` VARCHAR(100) NOT NULL,
    `fileSize` INTEGER NOT NULL,
    `checksum` VARCHAR(128) NOT NULL,
    `storagePath` VARCHAR(1024) NOT NULL,
    `url` VARCHAR(1024) NOT NULL,
    `capturedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdBy` VARCHAR(255) NOT NULL,
    `updatedAt` DATETIME(3) NULL,
    `updatedBy` VARCHAR(255) NULL,
    `deletedAt` DATETIME(3) NULL,
    `deletedBy` VARCHAR(255) NULL,

    UNIQUE INDEX `photos_checksum_key`(`checksum`),
    INDEX `idx_photo_turno`(`turnoId`),
    INDEX `idx_photo_checklist_uuid`(`checklistUuid`),
    INDEX `idx_photo_tipo`(`tipo`),
    INDEX `idx_photo_created_at`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
