export * from './create-escala.dto';
export * from './update-escala.dto';
export * from './escala-query.dto';
export * from './escala-response.dto';
export * from './escala-list-response.dto';
export * from './escala-assign.dto';
export * from './escala-agenda-query.dto';
export * from './escala-agenda-response.dto';
export * from './escala-horario-response.dto';
